print ("***********************************")
print ("Tugas Day 1 - Sistem Operasi B")
print ("***********************************")
print ("Nama : Mareta Putri Wardhana")
print ("NPM  : 21083010002")
print ("***********************************")
print ("Notes :")
print ("***********************************")
print ("Hello People")
print ("Ini adalah script bash pertamaku di linux")
